"""
audit_workbook.py
-----------------
GIPS Audit Workbook -- Multi-Sheet Institutional Excel Report
IQRE (Institutional Quantitative Reporting Engine)

Sheets
------
1. Decision_Units     -- Aggregated DCA sequences with GIPS risk metrics.
2. Data_Traceability  -- Cleaned source rows, each linked back to its
                         Decision Unit via Trade # and original Excel
                         row number (Data Lineage -- ARCHITECTURE.md §6).

Governance (2026 Protocols -- ARCHITECTURE.md §6):
    - Architecture as Authority : only mandated columns are exposed.
    - Data Lineage              : Source_Row column maps every data row
                                  to its exact position in tv_export_raw.xlsx.
    - Security Sandbox          : output written inside project /output dir.
    - PII Redaction             : Signal / account fields excluded.
    - Fail Fast                 : empty units or missing df columns raise
                                  AuditWorkbookError immediately.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import List, TYPE_CHECKING

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

if TYPE_CHECKING:
    from engine import DecisionUnit


# ---------------------------------------------------------------------------
# Audit guard
# ---------------------------------------------------------------------------
class AuditWorkbookError(RuntimeError):
    """Raised when workbook generation cannot proceed due to data issues."""


# ---------------------------------------------------------------------------
# Theme -- Institutional Navy (mirrors tear_sheet_gen.py)
# ---------------------------------------------------------------------------
_C_NAVY    = "0B2545"   # header fill
_C_LGRAY   = "F0F2F5"   # alternating even-row fill
_C_WHITE   = "FFFFFF"   # alternating odd-row fill
_C_DARK    = "141414"   # default body text
_C_WIN     = "006B2B"   # WIN outcome (forest green)
_C_LOSS    = "9E0000"   # LOSS outcome (deep red)
_C_TOTALS  = "DDE3EC"   # summary / totals row fill
_C_GOLD    = "B48C28"   # Sheet 2 tab accent
_C_SILVER  = "8C9BAB"   # Legal_Disclosure tab accent

# ---------------------------------------------------------------------------
# Legal Disclosure text — Institutional Hardening (full disclaimer)
# ---------------------------------------------------------------------------
_LEGAL_PARAGRAPHS = [
    ("IQRE v1.5 -- Institutional Recalibration Build", "title"),
    ("Institutional Quantitative Reporting Engine", "subtitle"),
    ("LEGAL DISCLOSURE & LIMITATION OF LIABILITY", "heading"),
    ("", "spacer"),
    (
        "This workbook is generated by the IQRE (Institutional Quantitative Reporting "
        "Engine) v1.5 Institutional Recalibration Build for institutional audit and informational "
        "purposes only. All data is sourced directly from TradingView export files "
        "without modification or interpolation.",
        "body",
    ),
    ("", "spacer"),
    ("1.  NO WARRANTY", "subheading"),
    (
        "No representation or warranty, express or implied, is made as to the accuracy, "
        "completeness, or fitness for purpose of any data, metric, or analysis contained "
        "in this workbook. All figures are derived directly from TradingView export data "
        "and are presented as computed by the IQRE engine without editorial adjustment.",
        "body",
    ),
    ("", "spacer"),
    ("2.  LIMITATION OF LIABILITY", "subheading"),
    (
        "The publisher, developers, and distributors of IQRE accept no liability for any "
        "investment decision, financial loss, regulatory action, or consequential damage "
        "arising from reliance on this report or any data contained herein. This document "
        "does not constitute investment advice, a solicitation, or a recommendation to "
        "buy or sell any financial instrument.",
        "body",
    ),
    ("", "spacer"),
    ("3.  PAST PERFORMANCE", "subheading"),
    (
        "Past performance is not indicative of future results. All metrics, including "
        "Net P&L, PNE (Peak Notional Exposure), MAE (Max Adverse Excursion), MWRR "
        "(Money-Weighted Rate of Return), and Ulcer Index, are historical and are "
        "provided solely for retrospective analytical purposes.",
        "body",
    ),
    ("", "spacer"),
    ("4.  CLASSIFICATION & CONFIDENTIALITY", "subheading"),
    (
        "This document is classified PROPRIETARY. Unauthorised reproduction, "
        "distribution, or disclosure of its contents, in whole or in part, to any "
        "party other than the intended recipient is strictly prohibited. Recipients "
        "must treat this document with the same degree of care as their own "
        "confidential information.",
        "body",
    ),
    ("", "spacer"),
    ("5.  GIPS ALIGNMENT", "subheading"),
    (
        "This report is produced in alignment with the Global Investment Performance "
        "Standards (GIPS) 2026 Governance Protocol. Compliance is structural and "
        "methodology-based; no formal GIPS certification is claimed or implied. "
        "The Adjusted Profit Factor and MWRR are computed on consolidated Decision "
        "Units, not on individual TradingView rows, consistent with GIPS composite "
        "definition requirements.",
        "body",
    ),
    ("", "spacer"),
    ("6.  DATA INTEGRITY", "subheading"),
    (
        "All computational outputs have been independently verified by the IQRE "
        "Mathematical Parity Verification Engine (verification.py). Any discrepancy "
        "between engine output and raw source data exceeding 1.0e-06 halts execution "
        "immediately under the Fail Fast governance protocol. The verification certificate "
        "is stored alongside this workbook in the output/ directory.",
        "body",
    ),
    ("", "spacer"),
    ("7.  ARCHITECT CONTACT", "subheading"),
    (
        "For schema compatibility queries, version update requests, integration support, "
        "or audit assistance, contact the Lead Decision Systems Architect: Harol Antibar. "
        "This system is maintained under active development in compliance with "
        "ARCHITECTURE.md as the single source of engineering authority.",
        "body",
    ),
]

# ---------------------------------------------------------------------------
# Number format strings (GIPS-standard representations)
# ---------------------------------------------------------------------------
_FMT_USD   = '$#,##0.00'           # monetary values  e.g. $1,969.22
_FMT_USD4  = '$#,##0.0000'         # high-precision prices  e.g. $1.0087
_FMT_INT   = '#,##0'               # integer counts
_FMT_FLOAT = '#,##0.000'           # non-monetary floats  e.g. 970.778
_FMT_PCT   = '0.00%'               # percentages stored as decimals (0.0291 → 2.91%)
_FMT_DATE  = 'YYYY-MM-DD HH:MM:SS' # ISO-8601 datetime


# ---------------------------------------------------------------------------
# Reusable style components
# ---------------------------------------------------------------------------
_THIN_SIDE = Side(border_style="thin", color="C8C8C8")
_BORDER    = Border(
    left=_THIN_SIDE, right=_THIN_SIDE,
    top=_THIN_SIDE,  bottom=_THIN_SIDE,
)


def _hdr_font() -> Font:
    return Font(name="Calibri", bold=True, color=_C_WHITE, size=11)


def _body_font(color: str = _C_DARK, bold: bool = False) -> Font:
    return Font(name="Calibri", size=10, color=color, bold=bold)


def _solid(color: str) -> PatternFill:
    return PatternFill("solid", fgColor=color)


def _align(h: str = "left", v: str = "center") -> Alignment:
    return Alignment(horizontal=h, vertical=v)


def _row_fill(data_row_idx: int) -> PatternFill:
    """Alternating fill: light-gray for even, white for odd (0-indexed)."""
    return _solid(_C_LGRAY if data_row_idx % 2 == 0 else _C_WHITE)


# ---------------------------------------------------------------------------
# Cell writers
# ---------------------------------------------------------------------------
def _write_header(
    ws,
    col: int,
    row: int,
    label: str,
    h_align: str = "center",
) -> None:
    """Write a single navy bold header cell."""
    c = ws.cell(row=row, column=col, value=label)
    c.font      = _hdr_font()
    c.fill      = _solid(_C_NAVY)
    c.alignment = _align(h_align)
    c.border    = _BORDER


def _write_cell(
    ws,
    row: int,
    col: int,
    value,
    fmt:         str | None  = None,
    h_align:     str          = "left",
    font_color:  str          = _C_DARK,
    bold:        bool         = False,
    fill:        PatternFill | None = None,
) -> None:
    """Write a single data cell with full formatting."""
    c = ws.cell(row=row, column=col, value=value)
    c.font      = _body_font(color=font_color, bold=bold)
    c.alignment = _align(h_align)
    c.border    = _BORDER
    if fill is not None:
        c.fill = fill
    if fmt is not None:
        c.number_format = fmt


# ---------------------------------------------------------------------------
# Column specs
# ---------------------------------------------------------------------------
# Each entry: (header label, col width, data h_align, number format)
_DU_COLS = [
    ("Trade ID",           10, "center", _FMT_INT),
    ("Entries",            10, "center", _FMT_INT),
    ("Net P&L (USDT)",     18, "right",  _FMT_USD),
    ("PNE (USDT)",         18, "right",  _FMT_USD),
    ("MAE (USDT)",         16, "right",  _FMT_USD),
    ("MAE %",              12, "center", _FMT_PCT),
    ("Outcome",            12, "center", None),
]

_TR_COLS = [
    ("Source Row (Excel)",     20, "center", _FMT_INT),
    ("Trade #",                12, "center", _FMT_INT),
    ("Type",                   16, "left",   None),
    ("Date (UTC)",             22, "left",   _FMT_DATE),
    ("Price (USDT)",           16, "right",  _FMT_USD4),
    ("Position Size",          16, "right",  _FMT_FLOAT),
    ("Position Value (USDT)",  22, "right",  _FMT_USD),
    ("Net P&L (USDT)",         18, "right",  _FMT_USD),
    ("Net P&L %",              14, "center", _FMT_PCT),
    ("Adverse Exc. (USDT)",    22, "right",  _FMT_USD),
    ("Adverse Exc. %",         18, "center", _FMT_PCT),
    ("Cumulative P&L (USDT)",  24, "right",  _FMT_USD),
]


# ---------------------------------------------------------------------------
# Sheet builders
# ---------------------------------------------------------------------------
def _build_decision_units(wb: Workbook, units: List) -> None:
    """
    Sheet 1: one row per Decision Unit (DCA-aggregated trade sequence).

    Columns : Trade ID | Entries | Net P&L | PNE | MAE | MAE % | Outcome
    Extras  : totals / averages row, frozen header, auto-filter.
    """
    ws = wb.create_sheet("Decision_Units")
    ws.sheet_properties.tabColor = _C_NAVY
    ws.row_dimensions[1].height = 24

    # -- header --
    for col, (label, width, align, _) in enumerate(_DU_COLS, start=1):
        _write_header(ws, col, 1, label, align)
        ws.column_dimensions[get_column_letter(col)].width = width

    # -- data rows --
    n = len(units)
    for row_idx, u in enumerate(units):
        xl_row = row_idx + 2
        ws.row_dimensions[xl_row].height = 18
        bg = _row_fill(row_idx)
        o_color = _C_WIN if u.outcome == "WIN" else _C_LOSS

        row_cells = [
            # (value,            fmt,       h_align,   font_color, bold)
            (u.trade_id,         _FMT_INT,  "center",  _C_DARK,    False),
            (u.entries,          _FMT_INT,  "center",  _C_DARK,    False),
            (u.net_pnl,          _FMT_USD,  "right",   _C_DARK,    False),
            (u.pne,              _FMT_USD,  "right",   _C_DARK,    False),
            (u.mae,              _FMT_USD,  "right",   _C_DARK,    False),
            (u.mae_pct / 100.0,  _FMT_PCT,  "center",  _C_DARK,    False),
            (u.outcome,          None,      "center",  o_color,    True),
        ]
        for col, (val, fmt, h, fc, bold) in enumerate(row_cells, start=1):
            _write_cell(ws, xl_row, col, val, fmt, h, fc, bold, bg)

    # -- summary row --
    sr = n + 2                         # Excel row index for summary
    ws.row_dimensions[sr].height = 20
    sf = _solid(_C_TOTALS)
    last_data = n + 1                  # last data Excel row

    wins = sum(1 for u in units if u.outcome == "WIN")

    summary_cells = [
        # col  value/formula                         fmt        h_align  bold
        (1,  "TOTALS / AVG",                         None,      "center", True),
        (2,  f"=SUM(B2:B{last_data})",               _FMT_INT,  "center", True),
        (3,  f"=SUM(C2:C{last_data})",               _FMT_USD,  "right",  True),
        (4,  f"=AVERAGE(D2:D{last_data})",           _FMT_USD,  "right",  True),
        (5,  f"=MAX(E2:E{last_data})",               _FMT_USD,  "right",  True),
        (6,  f"=MAX(F2:F{last_data})",               _FMT_PCT,  "center", True),
        (7,  f"{wins} WIN / {n - wins} LOSS",        None,      "center", True),
    ]
    for col, val, fmt, h, bold in summary_cells:
        _write_cell(ws, sr, col, val, fmt, h, _C_NAVY, bold, sf)

    # -- freeze & filter --
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = (
        f"A1:{get_column_letter(len(_DU_COLS))}{last_data}"
    )


def _build_traceability(wb: Workbook, df: pd.DataFrame) -> None:
    """
    Sheet 2: one row per cleaned source row, sorted by Trade # for easy
    cross-referencing with Sheet 1.

    The 'Source Row (Excel)' column contains the original row number
    (index + 2, accounting for the 1-indexed header) from the source
    tv_export_raw.xlsx 'List of trades' sheet, providing a verifiable
    audit trail per GIPS Data Lineage requirements.
    """
    ws = wb.create_sheet("Data_Traceability")
    ws.sheet_properties.tabColor = _C_GOLD
    ws.row_dimensions[1].height = 24

    # -- header --
    for col, (label, width, align, _) in enumerate(_TR_COLS, start=1):
        _write_header(ws, col, 1, label, align)
        ws.column_dimensions[get_column_letter(col)].width = width

    # -- sort display order: Trade # then by original source row --
    df_display = df.copy()
    df_display["_src_row"] = df_display.index + 2   # Excel row in source file
    df_display = df_display.sort_values(
        ["Trade #", "_src_row"], ascending=[True, True]
    ).reset_index(drop=True)

    # -- data rows --
    for row_idx, (_, row) in enumerate(df_display.iterrows()):
        xl_row = row_idx + 2
        ws.row_dimensions[xl_row].height = 18
        bg = _row_fill(row_idx)

        # Adverse excursion can be negative (adverse = below entry)
        adv_usdt    = row["Adverse excursion USDT"]
        adv_pct     = row["Adverse excursion %"] / 100.0
        net_pnl_pct = row["Net P&L %"] / 100.0

        row_cells = [
            # (value,                          fmt,        h_align)
            (int(row["_src_row"]),             _FMT_INT,   "center"),
            (int(row["Trade #"]),              _FMT_INT,   "center"),
            (row["Type"],                      None,       "left"),
            (row["Date"],                      _FMT_DATE,  "left"),
            (row["Price"],                     _FMT_USD4,  "right"),
            (row["Size"],                      _FMT_FLOAT, "right"),
            (row["Position size (value)"],     _FMT_USD,   "right"),
            (row["Profit"],                    _FMT_USD,   "right"),
            (net_pnl_pct,                      _FMT_PCT,   "center"),
            (adv_usdt,                         _FMT_USD,   "right"),
            (adv_pct,                          _FMT_PCT,   "center"),
            (row["Cumulative P&L USDT"],       _FMT_USD,   "right"),
        ]
        for col, (val, fmt, h) in enumerate(row_cells, start=1):
            _write_cell(ws, xl_row, col, val, fmt, h, fill=bg)

    n_rows = len(df_display)
    # -- freeze & filter --
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = (
        f"A1:{get_column_letter(len(_TR_COLS))}{n_rows + 1}"
    )


# ---------------------------------------------------------------------------
# Sheet 3: Legal Disclosure  (Institutional Hardening)
# ---------------------------------------------------------------------------
def _build_legal_disclosure(wb: Workbook, utc_ts: str) -> None:
    """
    Sheet 3: Full legal disclaimer, limitation of liability, and governance
    disclosure.  Required by the Institutional Hardening specification.

    Layout
    ------
    - Column A : Text content (width 110, word-wrap enabled)
    - Column B : Generation timestamp metadata (narrow, right-aligned)
    """
    ws = wb.create_sheet("Legal_Disclosure")
    ws.sheet_properties.tabColor = _C_SILVER
    ws.column_dimensions["A"].width = 112
    ws.column_dimensions["B"].width = 32

    # Timestamp header row
    ts_cell = ws.cell(row=1, column=2, value=f"Generated (UTC): {utc_ts}")
    ts_cell.font      = Font(name="Calibri", size=9, italic=True, color="666666")
    ts_cell.alignment = Alignment(horizontal="right", vertical="center")

    xl_row = 2
    for text, style in _LEGAL_PARAGRAPHS:
        ws.row_dimensions[xl_row].height = 6 if style == "spacer" else None

        if style == "spacer":
            xl_row += 1
            continue

        c = ws.cell(row=xl_row, column=1, value=text)
        c.alignment = Alignment(
            horizontal="left",
            vertical="top",
            wrap_text=(style == "body"),
        )
        c.border = Border()  # no borders on this sheet

        if style == "title":
            c.font = Font(name="Calibri", bold=True, size=16, color=_C_NAVY)
            ws.row_dimensions[xl_row].height = 28
        elif style == "subtitle":
            c.font = Font(name="Calibri", size=12, italic=True, color="444444")
            ws.row_dimensions[xl_row].height = 20
        elif style == "heading":
            c.font = Font(name="Calibri", bold=True, size=13, color=_C_NAVY)
            ws.row_dimensions[xl_row].height = 22
            c.fill = _solid("DDE3EC")
        elif style == "subheading":
            c.font = Font(name="Calibri", bold=True, size=11, color=_C_NAVY)
            ws.row_dimensions[xl_row].height = 18
        elif style == "body":
            c.font = Font(name="Calibri", size=10, color=_C_DARK)
            ws.row_dimensions[xl_row].height = 52

        xl_row += 1

    # Footer stamp
    xl_row += 1
    stamp = ws.cell(
        row=xl_row, column=1,
        value=(
            f"IQRE v1.5 -- Institutional Recalibration Build  |  "
            f"GIPS 2026 Governance Protocol  |  "
            f"Audit Timestamp: {utc_ts}"
        ),
    )
    stamp.font      = Font(name="Calibri", size=8, italic=True, color="888888")
    stamp.alignment = Alignment(horizontal="left", vertical="center")
    ws.row_dimensions[xl_row].height = 16


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def generate_audit_workbook(
    units: List,
    df: pd.DataFrame,
    output_path: Path,
) -> Path:
    """
    Generate the GIPS-aligned audit workbook and save it to output_path.

    Parameters
    ----------
    units       : list[DecisionUnit] from IQREAnalytics.aggregate_sequences()
    df          : cleaned source DataFrame (engine.df after aggregation,
                  original pandas index preserved for Data Lineage)
    output_path : destination path; parent directories created automatically

    Returns
    -------
    Resolved Path of the saved .xlsx file.

    Raises
    ------
    AuditWorkbookError
        If units is empty or df is missing required columns.
    """
    if not units:
        raise AuditWorkbookError(
            "[AUDIT FAIL] Cannot generate workbook: no Decision Units found."
        )

    required_df_cols = {
        "Trade #", "Type", "Date", "Price", "Size",
        "Position size (value)", "Profit", "Net P&L %",
        "Adverse excursion USDT", "Adverse excursion %",
        "Cumulative P&L USDT",
    }
    missing = required_df_cols - set(df.columns)
    if missing:
        raise AuditWorkbookError(
            f"[AUDIT FAIL] DataFrame missing columns: {sorted(missing)}"
        )

    output_path = Path(output_path).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    utc_now = datetime.now(timezone.utc)
    utc_ts  = utc_now.strftime("%Y-%m-%d %H:%M:%S UTC")

    wb = Workbook()
    wb.remove(wb.active)          # discard default empty sheet

    # -- Excel metadata / document properties (Institutional Hardening) -------
    wb.properties.title          = "IQRE Institutional Audit Data — Production Build"
    wb.properties.subject        = "GIPS-Aligned Quantitative Reporting"
    wb.properties.creator        = "IQRE v1.5 -- Institutional Recalibration Build"
    wb.properties.lastModifiedBy = f"IQRE Audit Engine  |  {utc_ts}"
    wb.properties.description    = (
        f"Generated: {utc_ts}  |  "
        "GIPS 2026 Governance Protocol  |  "
        "Classification: Proprietary  |  "
        "Architect: Harol Antibar"
    )
    wb.properties.keywords = "GIPS; IQRE; DCA; PNE; MAE; institutional; production"
    wb.properties.category = "Institutional Audit"
    wb.properties.created  = utc_now

    _build_decision_units(wb, units)
    _build_traceability(wb, df)
    _build_legal_disclosure(wb, utc_ts)

    wb.save(str(output_path))
    return output_path


if __name__ == "__main__":
    print("[AUDIT WORKBOOK] Invoke via main.py -- do not run directly.")
